baseURL = 'https://tunefish.at/'
languageCode = 'de-AT'
title = 'tunefish Blog'
theme = 'm10c'

[outputs]
home = [ "HTML" ]

[menu]
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Publications"
    url = "/publications/"
    weight = 3

[params]
    author = 'tunefish'
    avatar = 'img/tunalogo.png'
    description = 'IT Research, Privacy, Hacking, Nonsense'
    menu_item_separator = '<br>'

[[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/tunefish777"

[[params.social]]
    icon = "mastodon"
    name = "Mastodon"
    url = "https://infosec.exchange/@tunefish"

[[params.social]]
    icon = "mail"
    name = "email"
    url = "mailto:tunefish@tunefish.at"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
